import { StyleSheet } from "react-native";
import { colors } from "../components/colors";
const { accent, black, primary, primarygray } = colors;
export const styles = StyleSheet.create({
  //Slider
  container: {
    fontFamily: "Roboto-Regular",
    paddingLeft: 20,
    paddingRight: 20,
    top: 70,
  },

  containerOnBoarding: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    backgroundColor: "#BF1FB1",
    padding: 10,
  },

  titleStyle: {
    fontFamily: "Roboto-Regular",
    padding: 10,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
  },
  introTitleStyle: {
    fontFamily: "Roboto-Regular",
    marginTop: 30,
    fontSize: 25,
    color: "white",
    textAlign: "left",
    marginBottom: 16,
    fontWeight: "bold",
    paddingLeft: 5,
    paddingRight: 5,
  },
  introTitleStyleAr: {
    fontFamily: "Roboto-Regular",
    marginTop: 30,
    fontSize: 25,
    color: "white",
    textAlign: "right",
    marginBottom: 16,
    fontWeight: "bold",
    paddingLeft: 5,
    paddingRight: 30,
  },
  introImageStyle: {
    marginTop: 30,
    width: 150,
    height: 150,
    //border raduis circle
    borderRadius: 150 / 2,
    //align the image in the center
    alignSelf: "center",
  },
  introTextStyle: {
    fontFamily: "Roboto-Regular",
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 18,
    color: "white",
    textAlign: "left",
    paddingTop: 30,
    lineHeight: 24,
  },
  introTextStyleAr: {
    fontFamily: "Roboto-Regular",
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 30,
    fontSize: 18,
    color: "white",
    textAlign: "right",
    paddingTop: 30,
    lineHeight: 24,
  },
  //RootStack
  containerRootStack: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 120,
  },
  //Card
  title: {
    fontFamily: "Roboto-Regular",
    color: "#444",
    fontWeight: "600",
  },
  text: {
    fontFamily: "Roboto-Regular",
    fontSize: 12,
    color: "#000",
    marginLeft: 25,
    fontWeight: "600",
  },
  selectedText: {
    fontFamily: "Roboto-Regular",
    marginLeft: 25,
    fontSize: 12,
    fontWeight: "600",
    color: "#BF1FB1",
  },
  //TextInputs
  textInput: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#f6f6f8",
    top: 10,
    height: 60,
    borderRadius: 30,
    padding: 20,
    fontSize: 15,
  },
  button: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#0872c3",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
  },
  textButton: {
    fontFamily: "Roboto-Regular",
    textTransform: "none",
    color: "white",
  },
  //Settings
  textStyleSettings: {
    fontFamily: "Roboto-Regular",
    color: "#BF1FB1",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 27,
    marginRight: 27,
    paddingTop: 30,
  },

  buttonSettings: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#BF1FB1",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
    top: 10,
    marginTop: 16,
  },
  textButtonSettings: {
    fontFamily: "Roboto-Regular",
    textTransform: "none",
    color: "white",
    fontSize: 16,
  },
  textButtonNavigateSettings: {
    fontFamily: "Roboto-Regular",
    textTransform: "none",
    color: "#000000",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 27,
    marginRight: 27,
    paddingTop: 15,
  },
  buttonNavigateSettings: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#fff",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
    top: 10,
    marginTop: 16,
  },
  //Dashboards
  gridView: {
    fontFamily: "Roboto-Regular",
    marginTop: 10,
    flex: 1,
  },

  itemContainer: {
    fontFamily: "Roboto-Regular",
    justifyContent: "center",
    borderRadius: 5,
    height: 180,
    backgroundColor: "#fff",
    boxShadow:
      "rgb(0 0 0 / 10%) 0px 0px 5px 0px, rgb(0 0 0 / 10%) 0px 0px 1px 0px",
  },
  itemName: {
    fontFamily: "Roboto-Regular",
    fontSize: 13,
    color: "#000",
    fontWeight: "bold",
    textAlign: "center",
  },

  //HotelsPage
  Loading: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    justifyContent: "center",
  },
  searchInput1: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "white",
    padding: 20,
    marginTop: 20,
    marginLeft: 10,
    border: 10,
    borderRadius: 10,
    width: "94%",
  },

  titleHotels: {
    fontFamily: "Roboto-Regular",
    color: "#000",
    textAlign: "center",
    fontWeight: "700",
    fontSize: 16,
    paddingTop: 20,
    marginEnd: 10,
  },
  lastCardView1: {
    fontFamily: "Roboto-Regular",
    marginTop: 40,
    flex: 1,
    height: "100%",
    justifyContent: "space-around",
    alignItems: "center",
    margin: 10,
    borderRadius: 20,
    padding: 35,
    marginBottom: "25%",
  },
  cardView1: {
    fontFamily: "Roboto-Regular",
    marginTop: 50,
    flex: 1,
    height: "100%",
    justifyContent: "space-around",
    alignItems: "center",
    margin: 10,
    borderRadius: 20,
    padding: 35,
  },
  TextHotels: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    paddingLeft: 10,
    paddingRight: 10,
  },
  DescriptionTextHotels: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    textAlign: "center",
    marginTop: 15,
  },
  // chatscreen
  containerChatScreen: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    backgroundColor: primarygray,
  },
  chatContainer: {
    fontFamily: "Roboto-Regular",
    flexGrow: 1,
    padding: 16,
    //backgroundColor: lightGray,
  },
  messageContainer: {
    fontFamily: "Roboto-Regular",
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 8,
    marginVertical: 8,
    maxWidth: "70%",
  },
  oddMessage: {
    fontFamily: "Roboto-Regular",
    alignSelf: "flex-start",
    backgroundColor: "#3D3B40",
  },
  evenMessage: {
    fontFamily: "Roboto-Regular",
    alignSelf: "flex-end",
    backgroundColor: "#525CEB",
  },
  messageText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "white",
    marginLeft: 10,
    paddingRight: 30,
  },
  userIcon: {
    marginRight: 10,
    color: "white",
  },
  inputContainer: {
    fontFamily: "Roboto-Regular",
    flexDirection: "row",
    alignItems: "center",
    //borderTopWidth: 1,
    borderTopColor: "black",
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  input: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 20,
    paddingHorizontal: 15,
    marginRight: 10,
    color: "black",
  },
  sendButton: {
    fontFamily: "Roboto-Regular",
    backgroundColor: accent,
    borderRadius: 8,
    height: 45,
    display: "flex",
    alignItems: "center",

    padding: 15,
  },
  sendButtonText: {
    fontFamily: "Roboto-Regular",
    color: "white",
    fontSize: 16,
    //textAlign: "center",
  },
  // clientscreen
  title: {
    fontFamily: "Roboto-Regular",
    flexDirection: "row",
    alignItems: "center",

    marginBottom: 16,
  },
  titleText: {
    fontFamily: "Roboto-Regular",
    fontSize: 20,
    color: black,
  },
  titleIcon: {
    fontFamily: "Roboto-Regular",
    marginRight: 10,
    color: accent,
  },
  containerClient: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    backgroundColor: primarygray,
    padding: 20,
  },
  cardView: {
    fontFamily: "Roboto-Regular",
    marginTop: 50,
    marginVertical: 10,
    borderRadius: 15,
    elevation: 3,
    backgroundColor: "#ffffff",
    shadowColor: accent,
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 2 },
    borderWidth: 1,
    borderColor: "white",
  },

  lastCardView: {
    fontFamily: "Roboto-Regular",
    marginVertical: 10,
    borderRadius: 15,
    elevation: 3,
    backgroundColor: "#ffffff",
    shadowColor: accent,
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    borderWidth: 1,
    borderColor: "white", // You can change the border color as needed
  },

  textHotels: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,

    marginBottom: 8,
    color: "#333",
  },
  descriptionTextHotels1: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    marginBottom: 5,
    marginLeft: 20,
    color: black,
  },

  loading: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  searchInput: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "white",
    padding: 20,
    marginTop: 20,
    border: 10,
    borderRadius: 10,
    width: "100%",
  },

  // Notifications
  containerNotifi: {
    fontFamily: "Roboto-Regular",
    flex: 1,
    padding: 16,
  },
  markAsUnreadButton: {
    fontFamily: "Roboto-Regular",
    flexDirection: "row",
    alignItems: "center",

    marginBottom: 16,
  },
  markAsUnreadIcon: {
    fontFamily: "Roboto-Regular",
    marginRight: 10,
    textAlign: "center",
    color: accent,
  },
  markAsUnreadText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: black,
  },
  notificationList: {
    fontFamily: "Roboto-Regular",
    flexGrow: 1,
  },
  notificationContainer: {
    fontFamily: "Roboto-Regular",
    display: "flex",
    flexDirection: "row",
    textAlign: "center",
    alignItems: "center",
    padding: 12,
    borderRadius: 8,
    marginVertical: 8,
    backgroundColor: accent,
  },
  dot: {
    fontFamily: "Roboto-Regular",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "white",
    marginLeft: 150,
  },
  notificationText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "white",
  },
  icon: {
    fontFamily: "Roboto-Regular",
    marginRight: 10,
    color: "white",
  },
});
