import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    paddingLeft: 20,
    paddingRight: 20,
    top: 70,
  },
  titleAr: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "right",
  },
  titleFr: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "left",
  },
  labelAr: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "right",
    fontWeight: "bold",
  },
  labelFr: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "left",
    fontWeight: "bold",
  },
  containerOnBoarding: {
    flex: 1,
    backgroundColor: "#5f9ea0",
    padding: 10,
  },

  titleStyle: {
    padding: 10,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
  },
  introTitleStyle: {
    marginTop: 30,
    fontSize: 25,
    color: "white",
    textAlign: "left",
    marginBottom: 16,
    fontWeight: "bold",
    paddingLeft: 5,
    paddingRight: 5,
  },
  introTitleStyleAr: {
    marginTop: 30,
    fontSize: 25,
    color: "white",
    textAlign: "right",
    marginBottom: 16,
    fontWeight: "bold",
    paddingLeft: 5,
    paddingRight: 30,
  },
  introImageStyle: {
    marginTop: 30,
    width: 150,
    height: 150,
    //align the image in the center
    alignSelf: "center",
  },
  introTextStyle: {
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 18,
    color: "white",
    textAlign: "left",
    paddingTop: 30,
    lineHeight: 24,
  },
  introTextStyleAr: {
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 30,
    fontSize: 18,
    color: "white",
    textAlign: "right",
    paddingTop: 30,
    lineHeight: 24,
  },
  containerRootStack: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 120,
  },
  title: {
    color: "#444",
    fontWeight: "600",
  },
  text: {
    fontSize: 12,
    color: "#000",
    marginLeft: 25,
    fontWeight: "600",
  },
  selectedText: {
    marginLeft: 25,
    fontSize: 12,
    fontWeight: "600",
    color: "#4d7e80",
  },
  containerEditPassword: {
    paddingLeft: 20,
    paddingRight: 20,
    top: 100,
  },
  textInputView: {
    marginBottom: 30,
  },
  textInput: {
    backgroundColor: "#f6f6f8",
    top: 10,
    height: 60,
    borderRadius: 30,
    padding: 20,
    fontSize: 15,
  },
  button: {
    backgroundColor: "#0872c3",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
  },
  textButton: {
    textTransform: "none",
    color: "white",
  },
  containerInformation: {
    paddingLeft: 20,
    paddingRight: 20,
    top: 70,
  },
  titleArInformation: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "right",
  },
  titleFrInformation: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "left",
  },
  labelArInformation: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "right",
    fontWeight: "bold",
  },
  labelFrInformation: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "left",
    fontWeight: "bold",
  },
  labelArReclamation: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "right",
    fontWeight: "bold",
  },
  labelFrReclamation: {
    position: "relative",
    top: 22.5,
    fontSize: 13,
    textAlign: "left",
    fontWeight: "bold",
  },
  containerReclamation: {
    justifyContent: "center",
    height: "100%",
    marginBottom: 50,
  },
  cameraReclamation: {
    flex: 1,
  },
  buttonContainerAReclamation: {
    position: "absolute",
    top: 5,
    left: 5,
  },
  cancelButtonContainerReclamation: {
    position: "absolute",
    top: 5,
    right: 5,
  },

  buttonTakePhotoContainerReclamation: {
    position: "absolute",
    left: "50%",
    transform: [{ translateX: -50 }],
    bottom: 25,
    alignItems: "center",
  },
  buttonReclamation: {
    flex: 1,
    alignSelf: "flex-end",
    alignItems: "center",
  },
  textReclamation: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },

  componentReclamation: {
    width: "80%",
    backgroundColor: "#fff",
    display: "flex",
    border: "none",
  },
  buttonContainerReclamation: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  containerSettings: {
    paddingTop: 60,
    paddingHorizontal: 16,
    backgroundColor: "#fff",
  },
  rowSettings: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  titleSettings: {
    color: "#444",
    fontWeight: "600",
  },
  buttonContainerSettings: {
    marginTop: 10,
  },
  textSettings: {
    fontSize: 14,
    color: "#000",
  },
  selectedTextSettings: {
    marginLeft: 5,
    fontSize: 14,
    fontWeight: "600",
    color: "tomato",
  },
  textStyleSettings: {
    color: "#4d7e80",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 27,
    marginRight: 27,
    paddingTop: 30,
  },
  titleNews: {
    color: "#000",
    textAlign: "center",
    fontWeight: "700",
    fontSize: 16,
    paddingTop: 20,
    marginEnd: 10,
  },

  buttonSettings: {
    backgroundColor: "#4d7e80",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
    top: 10,
    marginTop: 16,
  },
  textButtonSettings: {
    textTransform: "none",
    color: "white",
    fontSize: 16,
  },
  textButtonNavigateSettings: {
    textTransform: "none",
    color: "#000000",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 27,
    marginRight: 27,
    paddingTop: 15,
  },
  buttonNavigateSettings: {
    backgroundColor: "#fff",
    borderRadius: 30,
    width: "90%",
    marginLeft: 20,
    height: 60,
    padding: 10,
    top: 10,
    marginTop: 16,
  },
  gridView: {
    marginTop: 10,
    flex: 1,
  },
  FlatView: {
    marginTop: 20,
    flex: 1,
    //margin:30,
  },
  itemContainer: {
    justifyContent: "center",
    borderRadius: 5,
    height: 180,
    backgroundColor: "#fff",
    boxShadow:
      "rgb(0 0 0 / 10%) 0px 0px 5px 0px, rgb(0 0 0 / 10%) 0px 0px 1px 0px",
  },
  itemName: {
    fontSize: 13,
    color: "#000",
    fontWeight: "bold",
    textAlign: "center",
  },
  itemFlatListName: {
    fontSize: 16,
    color: "#000",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  itemFlatListContainer: {
    justifyContent: "center",
    borderRadius: 15,
    padding: 0,
    height: 200,
    margin: 15,
    backgroundColor: "#F0FFF",
    boxShadow:
      "rgb(0 0 0 / 10%) 14px -13px 6px 0px, rgb(0 0 0 / 10%) 0px 0px 1px 0px;",
  },
  itemDetailsName: {
    fontSize: 16,
    color: "#000",
    fontWeight: "bold",
    // textAlign: "center",
    marginBottom: 20,
  },
  itemDetailsContainer: {
    justifyContent: "center",
    borderRadius: 15,
    padding: 10,
    height: 210,
    backgroundColor: "#5f9ea0",
    // boxShadow:
    // "rgb(0 0 0 / 10%) 14px -13px 6px 0px, rgb(0 0 0 / 10%) 0px 0px 1px 0px;",
  },
  itemDetailsNormalText: {
    fontSize: 13,
    color: "#000",
    fontWeight: "bold",
    // textAlign: "center",
    marginBottom: 20,
  },
  FlatViewDetails: {
    marginTop: 20,
    flex: 1,
    margin: 30,
  },
  NewsView: {
    marginTop: 20,
    flex: 1,
  },
  itemNewsContainer: {
    justifyContent: "center",
    //borderRadius: 15,
    padding: 0,
    // height: 250,
    marginTop: 15,
    backgroundColor: "#fff",
    boxShadow:
      "rgb(0 0 0 / 10%) 14px -13px 6px 0px, rgb(0 0 0 / 10%) 0px 0px 1px 0px;",
  },
  itemNewsName: {
    fontSize: 16,
    color: "#000",
    fontWeight: "bold",
    textAlign: "left",
    paddingLeft: 15,
  },
  itemTextTitle: {
    marginTop: 15,
    fontSize: 16,
    color: "#000",
    fontWeight: "bold",
    textAlign: "center",
  },
  containerNews: {
    flex: 1,
    justifyContent: "space-around",
    alignItems: "center",
    margin: 10,
    borderRadius: 20,
  },
  cardView: {
    flex: 1,
    height: "100%",
    justifyContent: "space-around",
    alignItems: "center",
    margin: 10,
    borderRadius: 20,
    padding: 35,
  },
  ViewNews: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginVertical: 7,
  },
  TextNews: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "left",
    //flex: 1,
    paddingLeft: 10,
    paddingRight: 10,
  },
  TextNewsAr: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "right",
    //flex: 1,
    paddingLeft: 10,
    paddingRight: 10,
  },
  ImageNews: {
    width: 360,
    height: 175,
    borderRadius: 10,
  },
  DescriptionTextNews: {
    fontSize: 16,
    textAlign: "right",
    marginTop: 15,
  },
  DescriptionTextNewsAr: {
    fontSize: 16,
    textAlign: "left",
    marginTop: 15,
  },
  Loading: {
    flex: 1,
    justifyContent: "center",
  },
});
